name: Karate API Tests - Cert

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'pom.xml'
      - '**/*.feature'

  workflow_dispatch:  # Permite ejecución manual

jobs:
  run-karate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencias
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Ejecutar pruebas Karate con tag
        run: mvn clean test -Dkarate.env=cert -Dkarate.options="--tags @ServerUsuarios"

      - name: Guardar reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: karate-report
          path: target/cucumber-html-reports